$("document").ready(function() {
   LoadForm("include/persional.php", "#persional");
   LoadForm("include/additional.php", "#additional");
   LoadForm("include/education.php", "#education");
   LoadForm("include/employment_history.php", "#employment-history");

   // getSecureToken("asdas");
})

function LoadForm(url, id) {
   $.ajax({
       url: url,
       data: {},
       success: function(data) {
           $(id).html(data);
       }
   });
}

function getSecureToken(a) {

   $.ajax({
       url: "lib/getjson.php",
       dataType: "json",
       type: "POST",
       data: {},
       success: function(data) {
           // var jdata = JSON.parse(data);
           var CVX_SERVER = data.server_url;
           var CVX_USER = data.user_id;
           var CVX_SECURE_TOKEN = data.secure_token;
           console.log(data);

       }
   });
}




var CVX_SERVER = "http://cvxdemo.daxtra.com"; //- or any other Daxtra server
var CVX_USER = "TMA";
// var CVX_SECURE_TOKEN = "26KvJ0QvHkItmtGC0heXLf%2FAZCLxV9HCooWSuzaYGE1bhIqQPQblxj78u8je17RYBiWI7d1xE2kzFY%0ACXDEQ1bU%2Fw%3D%3D%0A"; //--  secure token provided to you by Daxtra

function handle_file_upload_field(file_upload_id) {
	var fileInput = document.getElementById(file_upload_id)
	var file = fileInput.files[0];

	var formData = new FormData();
	formData.append("file", file);
	// formData.append("account", CVX_SECURE_TOKEN + "; -turbo"); //-- add turbo processing option
	formData.append("account", CVX_USER + "; -turbo"); //-- add turbo processing option

	var xhr = prepare_xhr(my_cvx_return_handler);
	xhr.open("POST", CVX_SERVER + "/cvx/rest/api/v1/profile/full/json");
	xhr.send(formData);
}

// function handle_file_upload_field(file_upload_id) {
//    $.ajax({
//        url: "lib/getjson.php",
//        dataType: "json",
//        type: "POST",
//        data: {},
//        success: function(data) {
//            // var jdata = JSON.parse(data);
//            var CVX_SERVER = data.server_url;
//            var CVX_USER = data.user_id;
//            var CVX_SECURE_TOKEN = data.secure_token;

//            var fileInput = document.getElementById(file_upload_id)
//            var file = fileInput.files[0];

//            var formData = new FormData();
//            formData.append("file", file);
//            // formData.append("account", CVX_SECURE_TOKEN + "; -turbo"); //-- add turbo processing option
//            formData.append("account", CVX_USER + "; -turbo"); //-- add turbo processing option

//            var xhr = prepare_xhr(my_cvx_return_handler);
//            xhr.open("POST", CVX_SERVER + "/cvx/rest/api/v1/profile/full/json");
//            xhr.send(formData);

//        }
//    });



// }

function prepare_xhr(handler) {
   var xhr = new XMLHttpRequest();
   xhr.onreadystatechange = function(e) {
       var resp_text;
       if (xhr.readyState != 4) { return; }
       if (xhr.readyState == 4 && xhr.status == 200) {
           handler(this.responseText);
       } else {
           var ret_string;
           if (this.responseText.match(/^{/)) { //-- errors generated by CVX
               ret_string = this.responseText;
           } else { //-- other errors represent as json with status 999
               ret_string = '{"CSERRROR":{"message":"' + xhr.statusText + '", "code": 999}}';
           }
           handler(ret_string, xhr.status);
       }
   };

   return xhr;
}

function my_cvx_return_handler(json_response, error_code) {
   var profile_json = JSON.parse(json_response)
   if (error_code || profile_json.CSERROR) {
       //-- report error
       console.log(error_code);
   } else if (profile_json.StructuredResume) {
       //-- do something with profile_json which contains all
       //- extracted data
       console.log(profile_json);
   } else {
       
       // console.log(profile_json.Resume);
       getPersional(profile_json.Resume);
       getAdditional(profile_json.Resume);
       getEducation(profile_json.Resume);
       getEmployment(profile_json.Resume);
   }

}

function getPersional(resume) {
   
	var data = resume.StructuredResume;

	//===========Thong tin ca nhan=============
	var persionalName = data.PersonName;
	
	var firstName = (persionalName.GivenName ? persionalName.GivenName : ""); //Ten
	var midName = (persionalName.MiddleName[0] ? persionalName.MiddleName[0] : ""); //Ten Dem
	var lastName = (persionalName.FamilyName ? persionalName.FamilyName : ""); //Ho
	var nickName = (persionalName.PreferredGivenName ? persionalName.PreferredGivenName : ""); //Nick Nqme
	var sex = (persionalName.sex ? persionalName.sex : ""); //Gioi tinh
	var dob = (data.DOB ? data.DOB : ""); //ngay sinh
	var marital = (data.MaritalStatus ? data.MaritalStatus : ""); // tinh trang hon nhan
	var title = ""; //Danh xung
	if (sex == 'male') {
	   title = "mr";
	} else if (sex == "female") {
	   title = "ms";
	}
   	//==============add thong tin ca nhan===============
	$('#first-name').val(firstName);
	$('#middle-name').val(midName);
	$('#last-name').val(lastName);
	$('#nickname').val(nickName);
	$('#sex').val(sex);
	$('#dob').val(dob);
	$('#marital').val(marital);
	$('#title').val(title);

   	//===========Thong tin lien lac=============
   	var contact = data.ContactMethod;

   	var email = (contact.InternetEmailAddress_main ? contact.InternetEmailAddress_main : "");
   	var phone = (contact.Telephone_home ? contact.Telephone_home : "");
   	var addr = contact.PostalAddress_main.AddressLine +","+ contact.PostalAddress_main.Municipality+","+contact.PostalAddress_main.CountryCode;

   	$('#first-line').val(addr);
   	$('#email-1').val(email);
   	$('#mobile-phone').val(phone);
   	//==============Skill============
   	var skills = data.Competency;
   	var i;
   	$("#skill-person").html("");
   	for (i = 0; i < skills.length; i++){
   		var skill = skills[i];
   		var subString = "Skill";
   		if (skill.description.includes(subString)){
   			var str = '<span class="label label-primary">'+skill.skillName+'</span>';
   			$("#skill-person").append(str);
   		}
   	}

   // ContactDetail(data);
   // Skill(data);
}


function getAdditional(resume){
	var data = resume.ExperienceSummary;
	var sumary = data.ExecutiveBrief;
	$("#executive-summary").val(sumary);
	var hobbies = (resume.StructuredResume.Hobbies ? resume.StructuredResume.Hobbies : "");
	$("#hobbies").val(hobbies);
}

function getEducation(resume){
	console.log(resume);
	var edus = (resume.StructuredResume.EducationHistory ? resume.StructuredResume.EducationHistory : {});
	var i;
	// $("#education tbody").html("");
	for (i = 0; i < edus.length; i++){
		var edu = edus[i];
		console.log(edu);

		var university = (edu.SchoolName ? edu.SchoolName : ""); // truong
		var major =  (edu.Major ? edu.Major : ""); //chuyen nganh
		
		var start_year = (edu.StartDate ? edu.StartDate : '');
		var end_year = (edu.EndDate ? edu.EndDate : '');
		var degree ="";
		if (edu.Degree){
			var degree = (edu.Degree.degreeType ? edu.Degree.degreeType : "");
		}
		// var grate = (edu.Degree.degreeType ? edu.Degree.degreeType : "");
		var str = "<tr>";
		str += "<td>"+university+"</td>";
		str += "<td>"+major+"</td>";
		str += "<td>"+degree+"</td>";
		str += "<td>"+start_year+"</td>";
		str += "<td>"+end_year+"</td>";
		str += "<td></td>";
		str += "<td></td>";
		str += "<td></td>";
		$("#education tbody").append(str);
	} 
}

function getEmployment(resume){
	var employs = (resume.StructuredResume.EmploymentHistory ? resume.StructuredResume.EmploymentHistory : {});
	var i;
	for (i = 0; i < employs.length; i++){
		var employ = employs[i];

		var company = (employ.EmployerOrgName ? employ.EmployerOrgName : "Frelancer"); // truong
		var position =  (employ.JobArea ? employ.JobArea : ""); //chuyen nganh
		var start_year = (employ.StartDate ? employ.StartDate : "");
		var end_year = (employ.EndDate ? employ.EndDate : "Present");

		var description = (employ.Description ? employ.Description : "");
		var reason = "";
		// var grate = (edu.Degree.degreeType ? edu.Degree.degreeType : "");
		var str = '<table class="table bg-info table-bordered">';
	    str += '<tr>';
	    str += '<td> <p>Company Name</p></td>';
	    str += '<td> <input type="text" class="form-control" id="company-name" value="'+company+'"></td>';
	    str += '<td><p>Position title</p></td>';
	    str += '<td><input type="text"  class="form-control" id="position-title" value="'+position+'"></td>';
	    str += '</tr>';
	    str += '<tr>' ; 
	    str += '<td> From Date</td>';
	    str += '<td><span><input type="text" id="from-date" value="'+start_year+'"></span>'; 
	    str += '<span> To Date  <input type="text" id="to-date" value="'+end_year+'"></span></td>';           
	    str += '<td><p>Reason for Leaving</p></td>';               
	    str += '<td><input type="text" class="form-control" id="reason" value="'+reason+'"></td>';           
	    str += '</tr>';
	    str += '<tr><td><p>Main Duties </p></td><td colspan="3">';
	    str += '<textarea class="form-control" rows="5" id="executive-summary">'+description+'</textarea>';
	    str += '</td></tr>';           
	                   
		$("#employment-history").append(str);
	} 
}
// function handle_file_upload_field(file_upload_id) {
//     var fileInput = document.getElementById(file_upload_id)
//     var file = fileInput.files[0];

//     var formData = new FormData();
//     formData.append("file", file);
//     formData.append("account", CVX_SECURE_TOKEN + "; -turbo"); //-- add turbo processing option
//     // formData.append("TMA", "TMA; -turbo"); //-- add turbo processing option

//     var xhr = prepare_xhr(my_cvx_return_handler_phase1);
//     xhr.open("POST", CVX_SERVER + "/cvx/rest/api/v1/profile/full/json");
//     xhr.send(formData);
// }


// function prepare_xhr(handler) {
//     var xhr = new XMLHttpRequest();
//     xhr.onreadystatechange = function(e) {
//         var resp_text;
//         if (xhr.readyState != 4) { return; }
//         if (xhr.readyState == 4 && xhr.status == 200) {
//             console.log(this.responseText)
//             handler(this.responseText);
//         } else {
//             var ret_string;
//             if (this.responseText.match(/^{/)) { //-- errors generated by CVX
//                 ret_string = this.responseText;
//             } else { //-- other errors represent as json with status 999
//                 ret_string = '{"CSERRROR":{"message":"' + xhr.statusText + '", "code": 999}}';
//             }
//             handler(ret_string, xhr.status);
//         }
//     };

//     return xhr;
// }



// function my_cvx_return_handler_phase1(json_response, error_code) {
//     var profile_json = JSON.parse(json_response);

//     if (error_code || profile_json.CSERROR) {
//         //-- report error
//         console.log(profile_json);
//         return;
//     } else if (profile_json.StructuredResume) {
//         //-- do something with profile_json which contains
//         //-- only personal data: name and contact details
//         console.log(profile_json.StructuredResume);
//     }


//     //--  get full profile -----
//     if (profile_json.phase2_token) {
//         var xhr = prepare_xhr(my_cvx_return_handler_phase2);
//         xhr.open("GET", CVX_SERVER + "/cvx/rest/api/v1/data" +
//             "?token=" + profile_json.phase2_token)
//         xhr.send()
//     }
// }

// function my_cvx_return_handler_phase2(json_response, error_code) {
//     var profile_json = JSON.parse(json_response)
//     if (error_code || profile_json.CSERROR) {
//         //-- report error
//         alert("loi");
//     } else if (profile_json.StructuredResume) {
//         //-- do something with profile_json which contains all
//         //- extracted data
//         console.log(profile_json)
//     }
// }
